"""job salesperson

Revision ID: 1d79130f277d
Revises: ba3cf365d74e
Create Date: 2026-07-15 15:40:31.659703

"""
from alembic import op
import sqlalchemy as sa


revision = '1d79130f277d'
down_revision = 'ba3cf365d74e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('salesperson', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'salesperson')
    # ### end Alembic commands ###
