"""job measure date

Revision ID: 3daec98a4ffa
Revises: e23f56c7cee9
Create Date: 2026-07-15 05:50:52.969879

"""
from alembic import op
import sqlalchemy as sa


revision = '3daec98a4ffa'
down_revision = 'e23f56c7cee9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('measure_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'measure_date')
    # ### end Alembic commands ###
