"""phase updates

Revision ID: 42f2fa1a5c70
Revises: c97c818b17dc
Create Date: 2026-07-07 07:19:27.797786

"""
from alembic import op
import sqlalchemy as sa


revision = '42f2fa1a5c70'
down_revision = 'c97c818b17dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phase_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('noted_by', sa.String(length=255), nullable=True),
    sa.Column('noted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phase_updates_job_id'), 'phase_updates', ['job_id'], unique=False)
    op.create_index(op.f('ix_phase_updates_noted_at'), 'phase_updates', ['noted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phase_updates_noted_at'), table_name='phase_updates')
    op.drop_index(op.f('ix_phase_updates_job_id'), table_name='phase_updates')
    op.drop_table('phase_updates')
    # ### end Alembic commands ###
