"""job documents

Revision ID: 5987e3775191
Revises: 786307804093
Create Date: 2026-07-04 07:40:44.029316

"""
from alembic import op
import sqlalchemy as sa


revision = '5987e3775191'
down_revision = '786307804093'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_documents_job_id'), 'job_documents', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_documents_job_id'), table_name='job_documents')
    op.drop_table('job_documents')
    # ### end Alembic commands ###
