"""job notes

Revision ID: 64db2214b082
Revises: 3daec98a4ffa
Create Date: 2026-07-15 07:38:12.761753

"""
from alembic import op
import sqlalchemy as sa


revision = '64db2214b082'
down_revision = '3daec98a4ffa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_notes_created_at'), 'job_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_notes_job_id'), 'job_notes', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_notes_job_id'), table_name='job_notes')
    op.drop_index(op.f('ix_job_notes_created_at'), table_name='job_notes')
    op.drop_table('job_notes')
    # ### end Alembic commands ###
