"""quotes, quote line items, orders

Revision ID: 786307804093
Revises: 9cf312ac1af9
Create Date: 2026-07-04 05:48:19.901571

"""
from alembic import op
import sqlalchemy as sa


revision = '786307804093'
down_revision = '9cf312ac1af9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('draft', 'accepted', name='quotestatus', native_enum=False, length=16), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_job_id'), 'quotes', ['job_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('supplier', sa.Enum('everluxe', 'legacy', 'hardware', name='supplier', native_enum=False, length=16), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=True),
    sa.Column('confirmation_status', sa.Enum('pending', 'confirmed', 'rejected', name='confirmationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('ship_status', sa.Enum('not_shipped', 'scheduled', 'shipped', 'delivered', name='shipstatus', native_enum=False, length=16), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_job_id'), 'orders', ['job_id'], unique=False)
    op.create_index(op.f('ix_orders_quote_id'), 'orders', ['quote_id'], unique=False)
    op.create_table('quote_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=100), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=True),
    sa.Column('fin_end', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('list_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_line_items_quote_id'), 'quote_line_items', ['quote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_line_items_quote_id'), table_name='quote_line_items')
    op.drop_table('quote_line_items')
    op.drop_index(op.f('ix_orders_quote_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_job_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_quotes_job_id'), table_name='quotes')
    op.drop_table('quotes')
    # ### end Alembic commands ###
