"""hardware type column

Revision ID: 8c7ed4c6d19e
Revises: 9a6bb16b3638
Create Date: 2026-07-06 05:59:18.436809

"""
from alembic import op
import sqlalchemy as sa


revision = '8c7ed4c6d19e'
down_revision = '9a6bb16b3638'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hardware_selections', sa.Column('hardware_type', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hardware_selections', 'hardware_type')
    # ### end Alembic commands ###
