"""job code column

Revision ID: 9a6bb16b3638
Revises: 5987e3775191
Create Date: 2026-07-05 05:04:01.936284

"""
from alembic import op
import sqlalchemy as sa


revision = '9a6bb16b3638'
down_revision = '5987e3775191'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_code', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_jobs_job_code'), 'jobs', ['job_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_job_code'), table_name='jobs')
    op.drop_column('jobs', 'job_code')
    # ### end Alembic commands ###
