"""accounts, communities, jobs, selections

Revision ID: 9cf312ac1af9
Revises: 52654be58228
Create Date: 2026-07-04 05:34:45.168158

"""
from alembic import op
import sqlalchemy as sa


revision = '9cf312ac1af9'
down_revision = '52654be58228'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('builder', 'retail', name='accounttype', native_enum=False, length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=True)
    op.create_table('communities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('market', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'name', name='uq_community_account_name')
    )
    op.create_index(op.f('ix_communities_account_id'), 'communities', ['account_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('lot_number', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('job_type', sa.Enum('tract', 'custom', 'remodel', name='jobtype', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('quote', 'field_measure', 'ordered', 'delivery', 'install', 'quality', 'punch', 'warranty', 'closed', name='jobstatus', native_enum=False, length=32), nullable=False),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('warranty_start_date', sa.Date(), nullable=True),
    sa.Column('sales_contact_name', sa.String(length=255), nullable=False),
    sa.Column('sales_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('sales_contact_email', sa.String(length=255), nullable=True),
    sa.Column('field_contact_name', sa.String(length=255), nullable=False),
    sa.Column('field_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('field_contact_email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_account_id'), 'jobs', ['account_id'], unique=False)
    op.create_index(op.f('ix_jobs_community_id'), 'jobs', ['community_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('hardware_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=100), nullable=True),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('item', sa.String(length=255), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hardware_selections_job_id'), 'hardware_selections', ['job_id'], unique=False)
    op.create_table('room_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=100), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('cabinet_brand', sa.String(length=100), nullable=True),
    sa.Column('series', sa.String(length=100), nullable=True),
    sa.Column('door_style', sa.String(length=100), nullable=True),
    sa.Column('finish', sa.String(length=100), nullable=True),
    sa.Column('wood_species', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_selections_job_id'), 'room_selections', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_selections_job_id'), table_name='room_selections')
    op.drop_table('room_selections')
    op.drop_index(op.f('ix_hardware_selections_job_id'), table_name='hardware_selections')
    op.drop_table('hardware_selections')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_community_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_account_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_communities_account_id'), table_name='communities')
    op.drop_table('communities')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
