"""job po and pricing fields

Revision ID: ba3cf365d74e
Revises: 64db2214b082
Create Date: 2026-07-15 07:46:47.595506

"""
from alembic import op
import sqlalchemy as sa


revision = 'ba3cf365d74e'
down_revision = '64db2214b082'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('builder_po', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('po_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('jobs', sa.Column('cabinet_po', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('materials_cost', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('jobs', sa.Column('margin_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('jobs', sa.Column('margin_pct', sa.Numeric(precision=6, scale=3), nullable=True))
    op.add_column('jobs', sa.Column('po_status', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'po_status')
    op.drop_column('jobs', 'margin_pct')
    op.drop_column('jobs', 'margin_amount')
    op.drop_column('jobs', 'materials_cost')
    op.drop_column('jobs', 'cabinet_po')
    op.drop_column('jobs', 'po_amount')
    op.drop_column('jobs', 'builder_po')
    # ### end Alembic commands ###
