"""ordering checklists

Revision ID: c97c818b17dc
Revises: 8c7ed4c6d19e
Create Date: 2026-07-06 15:32:13.521640

"""
from alembic import op
import sqlalchemy as sa


revision = 'c97c818b17dc'
down_revision = '8c7ed4c6d19e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordering_checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('stage1_done', sa.Boolean(), nullable=False),
    sa.Column('stage2_done', sa.Boolean(), nullable=False),
    sa.Column('stage3_done', sa.Boolean(), nullable=False),
    sa.Column('stage4_done', sa.Boolean(), nullable=False),
    sa.Column('stage1_date', sa.Date(), nullable=True),
    sa.Column('stage2_date', sa.Date(), nullable=True),
    sa.Column('stage3_date', sa.Date(), nullable=True),
    sa.Column('stage4_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordering_checklists_job_id'), 'ordering_checklists', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ordering_checklists_job_id'), table_name='ordering_checklists')
    op.drop_table('ordering_checklists')
    # ### end Alembic commands ###
