"""job plan column

Revision ID: e23f56c7cee9
Revises: 42f2fa1a5c70
Create Date: 2026-07-07 10:08:56.167360

"""
from alembic import op
import sqlalchemy as sa


revision = 'e23f56c7cee9'
down_revision = '42f2fa1a5c70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('plan', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'plan')
    # ### end Alembic commands ###
