"""g/i codes and job costs

Revision ID: f8bffbec2dbc
Revises: 1d79130f277d
Create Date: 2026-07-15 15:52:17.253371

"""
from alembic import op
import sqlalchemy as sa


revision = 'f8bffbec2dbc'
down_revision = '1d79130f277d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('product_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('labor_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('labor_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('margin', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('other_labor_codes', sa.Text(), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_costs_job_id'), 'job_costs', ['job_id'], unique=True)
    op.add_column('jobs', sa.Column('g_code', sa.String(length=40), nullable=True))
    op.add_column('jobs', sa.Column('i_code', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'i_code')
    op.drop_column('jobs', 'g_code')
    op.drop_index(op.f('ix_job_costs_job_id'), table_name='job_costs')
    op.drop_table('job_costs')
    # ### end Alembic commands ###
